version: "3.9"
services:
  db:
    image: postgres
    container_name: pg_project2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: khodyka_db
    ports:
      - "5432:5432"
